[package]
name = "trauma_bug_hunt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.24"
fs_extra = "1.2.0"
lazy_static = "1.4.0"
tar = "0.4.38"
tokio = "1.21.2"
trauma = "2.1.0"
